const emotes = [
  ['images/bullets/4HEad-small.png', 'images/bullets/4HEad.png'],
  ['images/bullets/5Head-small.png', 'images/bullets/5Head.png'],
  ['images/bullets/COPIUM-small.png', 'images/bullets/COPIUM.png'],
  ['images/bullets/EZY-small.png', 'images/bullets/EZY.png'],
  [
    'images/bullets/FeelsAmazingMan-small.png',
    'images/bullets/FeelsAmazingMan.png',
  ],
  ['images/bullets/FeelsBadMan-small.png', 'images/bullets/FeelsBadMan.png'],
  ['images/bullets/FeelsOkayMan-small.png', 'images/bullets/FeelsOkayMan.png'],
  ['images/bullets/HYPERS-small.png', 'images/bullets/HYPERS.png'],
  ['images/bullets/KEKL-small.png', 'images/bullets/KEKL.png'],
  ['images/bullets/KEKLEO-small.png', 'images/bullets/KEKLEO.png'],
  ['images/bullets/KEKW-small.png', 'images/bullets/KEKW.png'],
  ['images/bullets/KEKWait-small.png', 'images/bullets/KEKWait.png'],
  ['images/bullets/LULW-small.png', 'images/bullets/LULW.png'],
  ['images/bullets/Madge-small.png', 'images/bullets/Madge.png'],
  ['images/bullets/monkaChrist-small.png', 'images/bullets/monkaChrist.png'],
  ['images/bullets/monkaHmm-small.png', 'images/bullets/monkaHmm.png'],
  ['images/bullets/monkaMEGA-small.png', 'images/bullets/monkaMEGA.png'],
  ['images/bullets/monkaOMEGA-small.png', 'images/bullets/monkaOMEGA.png'],
  ['images/bullets/monkaTOS-small.png', 'images/bullets/monkaTOS.png'],
  ['images/bullets/monkaW-small.png', 'images/bullets/monkaW.png'],
  ['images/bullets/OMEGALUL-small.png', 'images/bullets/OMEGALUL.png'],
  ['images/bullets/PauseChamp-small.png', 'images/bullets/PauseChamp.png'],
  ['images/bullets/peepoBlush-small.png', 'images/bullets/peepoBlush.png'],
  ['images/bullets/peepoFat-small.png', 'images/bullets/peepoFat.png'],
  ['images/bullets/peepoHappy-small.png', 'images/bullets/peepoHappy.png'],
  ['images/bullets/Pepega-small.png', 'images/bullets/Pepega.png'],
  ['images/bullets/PepeHands-small.png', 'images/bullets/PepeHands.png'],
  ['images/bullets/pepeJAM-small.png', 'images/bullets/pepeJAM.png'],
  ['images/bullets/PepeLaugh-small.png', 'images/bullets/PepeLaugh.png'],
  ['images/bullets/PepeThink-small.png', 'images/bullets/PepeThink.png'],
  ['images/bullets/pikachuS-small.png', 'images/bullets/pikachuS.png'],
  ['images/bullets/Pog-small.png', 'images/bullets/Pog.png'],
  ['images/bullets/Pogey-small.png', 'images/bullets/Pogey.png'],
  ['images/bullets/POGGERS-small.png', 'images/bullets/POGGERS.png'],
  ['images/bullets/Prayge-small.png', 'images/bullets/Prayge.png'],
  ['images/bullets/Sadge-small.png', 'images/bullets/Sadge.png'],
  ['images/bullets/sadKEK-small.png', 'images/bullets/sadKEK.png'],
  ['images/bullets/WICKED-small.png', 'images/bullets/WICKED.png'],
  [
    'images/bullets/widepeepoHappy-small.png',
    'images/bullets/widepeepoHappy.png',
  ],
  ['images/bullets/widepeepoSad-small.png', 'images/bullets/widepeepoSad.png'],
  ['images/bullets/YEP-small.png', 'images/bullets/YEP.png'],
];
let gifs = [
  ['images/gifs/borpaspin.webp'],
  ['images/gifs/modCheck.webp'],
  ['images/gifs/pepegacard.webp'],
  ['images/gifs/popCatRotate.webp'],
  ['images/gifs/ratjam.webp'],
  ['images/gifs/sadgeclap.webp'],
  ['images/gifs/vicksyspin.webp'],
  ['images/gifs/wickedsteer.webp'],
];
